# Generated by Django 5.1.5 on 2025-02-15 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_userprofile_city_alter_userprofile_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.TextField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='patronymic',
            field=models.TextField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.TextField(blank=True, max_length=12, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='surname',
            field=models.TextField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
