# Generated by Django 5.1.5 on 2025-02-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_city_alter_userprofile_city_alter_userprofile_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.TextField(max_length=100, verbose_name='Город'),
        ),
    ]
